### ISSUE TITLE
Bottom playback controls

### ISSUE THREAD

**Issue by canddoki** [orontee/argos#93] opened 2022-11-30 09:43 UTC
@orontee In daily use, we notice again and again that we always have to go to the Now-playing-tab when changing an album, stopping playback in the albumview, etc..
I think central player-controls that are always present would suit Argos very well :). On the attached picture a wish to Santa Claus ;-). What do you think about this topic?
![Argos-1](https://user-images.githubusercontent.com/107265121/204762001-6de90716-d66b-4a5a-8e6e-1e9132031e94.jpg)

**Comment by orontee** [comment] 2022-11-30 12:13
Yes, I agree that the user experience when switching back from album details view to the playback tab is not that good... There's place for improvement. Let's design the next UI.

What do you expect when viewing the playing tab? Should the bottom widget you design be displayed?

One other remark: Isn't the proposed design too heavy? We don't need constant access to the gear button menu for example, right?

**Comment by canddoki** [comment] 2022-11-30 14:50
Thanks for your positive feedback.
In the current playing tab, I don't really expect anything different than before. Only that the player controls and the progress bar move to the new bottom widget. I personally think the stop button in the player controls is useful. Sometimes you decide to stop an album after a few tracks and switch to another album. Without the stop button you would have to go back to the playing tab and delete the "leftovers" from the queue. This button then also takes over the function of the recycle bin, so that this can be omitted. In short: the bottom widget should always be visible :).
I agree with you and want it as light as possible.
I've been looking for a place to put consume, shuffle, repeat, etc. and can't think of a better place and put them than behind the gear. Would you rather leave these buttons in the playing tab (above the bottom widget)?

**Comment by orontee** [comment] 2022-12-01 11:29
@canddoki Check the dedicated branch, it contains a working draft. 

I just moved the "add to tracklist", "edit playlist", etc. buttons from bottom to top.  This could be improved but also done in a second time.

Still have to test on my Rasp where the screen is rather small...

**Comment by canddoki** [comment] 2022-12-02 07:27
@orontee Thanks for the quick, first shot :). Pretty impressive for the short time :). Functionally, I could not find any major issues after a short test.
I use a 7 inch display with a resolution of 800 x 480 px. What display are you using?
Here are my impressions from last night:

![argos-library-tab](https://user-images.githubusercontent.com/107265121/205234673-d6c1300e-d697-43aa-ab40-d867d3c113e8.png)

![argos-albumdetails](https://user-images.githubusercontent.com/107265121/205234695-f0b782a7-046f-44d7-b43c-1a281d841f7e.png)

![argos-tracklist](https://user-images.githubusercontent.com/107265121/205234743-ce932979-b4f4-44f0-8abf-3d2df1c13f90.png)

![argos-playlists](https://user-images.githubusercontent.com/107265121/205234755-7cf06f74-055e-4344-99a9-ceb932ffa656.png)

> Bottom widget not visible in album details view

The bottom widget is visible everywhere, except in the playing(new tracklist)-tab

The height of the bottom widget could be reduced to the height of the title bar (by about 40%). It looks lighter and it might help to solve the default-window-height-problem.
Also the height of the buttons - they could be the same height as the tab buttons in the title bar.
The font size could be the same as the cover captions in albums view.
The progress bar and position / duration not yet visible in the bottom widget.
Is it possible that the bottom widget is a bit darker so that it stands out a bit (like the title bar)?

>  Test if there's no regression with "volume button" feature

I will test at the weekend.

**Comment by orontee** [comment] 2022-12-02 18:11
> @orontee Thanks for the quick, first shot :). 

Welcome!

> Pretty impressive for the short time :). Functionally, I could not find any major issues after a short test. I use a 7 inch display with a resolution of 800 x 480 px. What display are you using?

Same here.

> Here are my impressions from last night:
> The bottom widget is visible everywhere, except in the playing(new tracklist)-tab

Yep, this is expected behavior.

> The height of the bottom widget could be reduced to the height of the title bar (by about 40%). 
> (...) Also the height of the buttons
> (...) The font size could be the same as the cover captions 

Should be the case with the last version.

> The progress bar and position / duration not yet visible in the bottom widget. 

Expected: Space is for track and artists name rather than position. I don't think we often interact with time position; Needless to say, could be added later if we found good reasons (maybe display position and total duration without slider?).

> Is it possible that the bottom widget is a bit darker so that it stands out a bit (like the title bar)?

Should be done through CSS; Try:
```
#condensed-playing-box {
  background-color: red;
}
```

![image](https://user-images.githubusercontent.com/2065954/205358261-e7ba977c-c522-4fa5-8048-564f8a0c8b3d.png)

> > Test if there's no regression with "volume button" feature
> 
> I will test at the weekend.

Thanks!

**Comment by orontee** [comment] 2022-12-03 08:17
I added some CSS identifiers to easy appearance customization.  With the following CSS, the user experience with new UI is pretty good.

```
$ cat ~bob/.config/gtk-3.0/gtk.css 
tooltip, .tooltip { border-radius: 0px; }

* {
    font-size: 13pt;
}

#playlist-button-box buttonbox button,
#album-details-button-box button,
#condensed-playing-box-playback-controls-box button {
    min-width: 60px;
    min-height: 30px;
}

#playlist-button-box > button {
    min-width: 30px;
    min-height: 30px;
}

#tracklist-button-box image {
  min-height: 30px;
  min-width: 30px;
}

.titlebar button {
  min-height: 30px;
  min-width: 30px;
}
```

**Comment by canddoki** [comment] 2022-12-03 20:35
Yeah, looks very good and also thanks a lot for the gtk.css 👍.

![image](https://user-images.githubusercontent.com/107265121/205461017-3e0a8420-f77d-44a6-8862-631397ba178b.png)

Definitely a bit of a perfectionist: Can the bottom widget be about 2-3 px wider on the left and right ;)?

> Test if there's no regression with "volume button" feature.

The volume control does not conflict with the play buttons.

> Expected: Space is for track and artists name rather than position. I don't think we often interact with time position.

Yes you are right. Come to think of it, we haven't used the slider yet.

What is the reason that you don't show the bottom widget in the playing-tab?

**Comment by orontee** [comment] 2022-12-03 21:34
> (...) Definitely a bit of a perfectionist: Can the bottom widget be about 2-3 px wider on the left and right ;)?

Sorry I am not sure I understand what you're asking for... I see on the screenshot you posted that the left side of the track image is not aligned with the left border of the album list view; Is that the problem?

> > Test if there's no regression with "volume button" feature.
> 
> The volume control does not conflict with the play buttons.

Good to now.

> > Expected: Space is for track and artists name rather than position. I don't think we often interact with time position.
> 
> Yes you are right. Come to think of it, we haven't used the slider yet.

On issue 94, there's  a branch the scale, time position and track length in bottom widget. Look nice on desktop, but the scale fails to resize on small screens, labels span two lines: Broken layout has I expect. No idea, not really motivated to fix it right now.

> What is the reason that you don't show the bottom widget in the playing-tab?

We'd then have two identical images, two previous, play/pause, next buttons, two track and artist labels, right? And less space for the tracklist?

**Comment by orontee** [comment] 2022-12-03 21:39
> > (...) Definitely a bit of a perfectionist: Can the bottom widget be about 2-3 px wider on the left and right ;)?
> 
> Sorry I am not sure I understand what you're asking for... I see on the screenshot you posted that the left side of the track image is not aligned with the left border of the album list view; Is that the problem?

Fixed with commit 1edc9d9.

**Comment by canddoki** [comment] 2022-12-03 21:51
It's not really a problem, but yes I mean the alignment to the border - thanks for fixing.

**Comment by canddoki** [comment] 2022-12-03 22:03
> We'd then have two identical images, two previous, play/pause, next buttons, two track and artist labels, right? And less space for the tracklist?

At first view, I only thought of the optical consistency. The duplications are, of course, a waste of space.

**Comment by orontee** [comment] 2022-12-03 22:56
The new layout seems to be quite usable as is, and my perception is that it's a great improvement. Nice suggestion @canddoki . I think I'll soon squash all commits on the feature branch and merge to main branch.

**Comment by canddoki** [comment] 2022-12-03 23:22
Yes, many thanks and happy Sunday 😊.

**Closed** 2022-12-04 09:14 UTC
Labels: enhancement
